#!/usr/bin/env bash

USERNAME=evgenkor
IMAGE=zeropool-console
VERSION=0.3.6

yarn build:prod && \
docker build -f Dockerfile.prod -t $USERNAME/$IMAGE:latest . && \
docker tag $USERNAME/$IMAGE:latest $USERNAME/$IMAGE:$VERSION && \
docker push $USERNAME/$IMAGE:latest && \
docker push $USERNAME/$IMAGE:$VERSION
