#!/usr/bin/env bash
cd ../libzeropool-rs/libzeropool-rs-wasm && \
./scripts/build && \
cd -

cd ../zeropool-api-js && \
yarn upgrade libzeropool-rs-wasm-web && \
yarn build && \

cd -
export EVM_RPC=''
export RELAYER_URL=''
export TOKEN_ADDRESS=''
export MINTER_ADDRESS=''
export CONTRACT_ADDRESS=''
yarn upgrade zeropool-api-js && \
yarn dev
