window.EVM_RPC = '$EVM_RPC';
window.RELAYER_URL = '$RELAYER_URL';
window.CONTRACT_ADDRESS = '$CONTRACT_ADDRESS';
window.TOKEN_ADDRESS = '$TOKEN_ADDRESS';
window.TRANSFER_PARAMS_URL = '$TRANSFER_PARAMS_URL';
window.TREE_PARAMS_URL = '$TREE_PARAMS_URL';
window.TRANSFER_VK_URL = '$TRANSFER_VK_URL';
window.TREE_VK_URL = '$TREE_VK_URL';
