window.NETWORK = '$NETWORK'.toLowerCase();
window.RPC_URL = '$RPC_URL';
window.RELAYER_URL = '$RELAYER_URL';
window.CONTRACT_ADDRESS = '$CONTRACT_ADDRESS';
window.TOKEN_ADDRESS = '$TOKEN_ADDRESS';
window.TRANSACTION_URL = '$TRANSACTION_URL';
window.DELEGATED_DEPOSITS_ADDRESS = '$DELEGATED_DEPOSITS_ADDRESS';
