name: Build console

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Installing dependecies
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install
    - name: Compile development version
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: build:dev
